// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC4XZPGa7KSgHimNkdKxYZT2Cy58V-4gA',
    appId: '1:640860070869:android:b2059bb161b8917b74935c',
    messagingSenderId: '640860070869',
    projectId: 'lmk-app-14864',
    storageBucket: 'lmk-app-14864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUiUa-bhJDMmOKxIzsT1eXyw6IrzhdQgw',
    appId: '1:640860070869:ios:80570f36f502797474935c',
    messagingSenderId: '640860070869',
    projectId: 'lmk-app-14864',
    storageBucket: 'lmk-app-14864.firebasestorage.app',
    androidClientId: '640860070869-gp1imupqkijfcupi2vp19g6vd6ols78e.apps.googleusercontent.com',
    iosClientId: '640860070869-vsvro6va0i6h26vunkv7bv8grqb1ir9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.lmk',
  );

}